import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('./gemini.ts', import.meta.url), 'utf8');
const htfRuleStart = source.indexOf('## Live FVG Trading System v1 Boundary');
const htfRuleEnd = source.indexOf('## Research Review P/L Interpretation Rule');
assert.ok(htfRuleStart >= 0, 'Gemini prompt must include the live FVG v1 boundary rule.');
assert.ok(htfRuleEnd > htfRuleStart, 'Gemini prompt must keep the HTF rule before research review rules.');

const htfRule = source.slice(htfRuleStart, htfRuleEnd);

assert.ok(source.includes('[DESK PLAN MANAGEMENT RULE]'));
assert.ok(source.includes('Name the HTF/session target/reaction level.'));
assert.ok(source.includes('Say T1 should be taken seriously.'));
assert.ok(source.includes('capped at or before T2 into that HTF/session structure'));
assert.ok(source.includes('reversal risk is live at that structure'));
assert.ok(source.includes('State both long-side bias and short-side bias when DeskState provides both'));
assert.ok(source.includes('next protected 5M line-in-the-sand map'));
assert.ok(source.includes('must not change app-owned entry, stop, T1, T2, risk, canExecute, model rules, or final approval'));

assert.ok(htfRule.includes('SetupType.FvgTradingSystemV1'));
assert.ok(htfRule.includes('FVG_TRADING_SYSTEM_V1'));
assert.ok(htfRule.includes('There is no active FVG Trading System v2'));
assert.ok(htfRule.includes('Runtime promotion may come only from app-owned deterministic scanner routes in the FVG_TRADING_SYSTEM_V1 family'));
assert.ok(htfRule.includes('These continuation routes are human-review/decision-support routes only'));
assert.ok(htfRule.includes('Historical setup names are aliases/context only'));
assert.ok(htfRule.includes('are not approved live setup routes'));
assert.ok(htfRule.includes('Narrative fallback cannot create HtfDrawContinuationAfterRaid'));
assert.ok(htfRule.includes('HtfDisplacementFvgContinuation'));
assert.ok(htfRule.includes('OpeningDriveFvgContinuation'));
assert.ok(htfRule.includes('AfterLunchDriveFvgContinuation'));
assert.ok(htfRule.includes('IntradayMssMicroContinuation'));
assert.ok(htfRule.includes('FailedPlanReversal'));
assert.ok(htfRule.includes('TurtleSoup'));
assert.ok(htfRule.includes('SweepMssFvgRetrace'));
assert.ok(htfRule.includes('Runtime promotion still requires HTF/15M story first'));
assert.ok(htfRule.includes('valid same-direction 15M parent FVG or battle zone'));
assert.ok(htfRule.includes('approved 15M displacement/MSS continuation context'));
assert.ok(htfRule.includes('nearest protected 5M structure stop'));
assert.ok(htfRule.includes('5M MSS may raise confidence for this FVG continuation context, but must not be invented'));
assert.ok(htfRule.includes('may not bypass deterministic entry, stop, target, session, screenshot-quality, final-pipeline, or canExecute gates'));
assert.ok(htfRule.includes('Risk exceeds standard limit. Human final decision required.'));
assert.ok(htfRule.includes('Potential MSS is not execution approval'));
assert.ok(htfRule.includes('15M potential MSS may support a candidate only when 5M MSS is confirmed'));
assert.ok(htfRule.includes('5M potential MSS may produce pending/developing states only and must not create a reversal-delivery candidate'));
assert.ok(htfRule.includes('Narrative fallback cannot create historical setup candidates and cannot approve execution'));
assert.equal(/approved .*pathway through SetupType\.(HtfDrawContinuationAfterRaid|HtfDisplacementMssContinuation|HtfDisplacementFvgContinuation|FailedPlanReversal)/.test(htfRule), false);
assert.ok(htfRule.includes('Morning 9:15-12:00 ET and Lunch/PM 12:00-16:00 ET'));
assert.ok(htfRule.includes('Do not use legacy pre-noon, lunch-only, or split-window cutoffs'));
assert.ok(htfRule.includes('HTF Context Sufficiency Visibility Rule'));
assert.ok(htfRule.includes('sufficient, partial, or insufficient'));
assert.ok(htfRule.includes('HTF is context only, not structural confirmation'));
assert.ok(htfRule.includes('cannot be used as candidate-promotion evidence'));
assert.ok(htfRule.includes('must not say HTF conflict confirmed, bullish structure confirmed, bearish structure confirmed, candidate ready'));
assert.ok(htfRule.includes('## Failed Plan Reversal Rule'));
assert.ok(htfRule.includes('When an app-owned plan fails its decision/reclaim level'));
assert.ok(htfRule.includes('re-evaluate 15M, 1H, 2H, and 4H structure first, then use 5M only as the execution trigger authority'));
assert.ok(htfRule.includes('Convert the failed plan level into an opposite-side decision level only when 15M, 1H, 2H, and 4H all confirm the opposite-side structure'));
assert.ok(htfRule.includes('If any of those HTF frames are missing, data-limited, neutral, mixed, or conflicting'));
assert.ok(htfRule.includes('failed original plan'));
assert.ok(htfRule.includes('failed decision level'));
assert.ok(htfRule.includes('opposite HTF MSS evidence'));
assert.ok(htfRule.includes('whether 5M has confirmed a fresh trigger'));
assert.ok(htfRule.includes('whether the trade is pending, confirmed, stale, or no fresh entry'));
assert.ok(htfRule.includes('This does not approve execution'));
assert.ok(htfRule.includes('The opposite-side plan still requires completed 5M trigger'));
assert.ok(htfRule.includes('## HTF Stack Confirmation Rule'));
assert.ok(htfRule.includes('Full confirmation: 15M + 1H + 2H + 4H align'));
assert.ok(htfRule.includes('Supported confirmation: legacy/context-only label. It is not enough to create a Failed Plan Reversal candidate.'));
assert.ok(htfRule.includes('Mixed: one or more of 15M/1H/2H/4H are neutral, data-limited, or unclear.'));
assert.ok(htfRule.includes('Conflict: one or more of 15M/1H/2H/4H materially oppose the move'));
assert.ok(htfRule.includes('5M remains execution authority. HTF stack can promote bias/state only.'));
assert.ok(htfRule.includes('## Failed Decision Level Role-Flip Rule'));
assert.ok(htfRule.includes('short-side resistance only after completed candle acceptance below that level'));
assert.ok(htfRule.includes('long-side support only after completed candle acceptance above that level'));
assert.ok(htfRule.includes('Do not role-flip from wick-only movement'));
assert.ok(htfRule.includes('Require fresh 5M trigger confirmation'));
assert.ok(htfRule.includes('## No-Chase Reversal Protection'));
assert.ok(htfRule.includes('no_fresh_entry or stale'));
assert.ok(htfRule.includes('must not create a late executable-style plan'));
assert.ok(htfRule.includes('## Failed Plan Reversal Output Format'));
assert.ok(htfRule.includes('## Failed Plan Boundary Rule'));
assert.ok(htfRule.includes('A failed long is not automatically a short'));
assert.ok(htfRule.includes('A failed short is not automatically a long'));
assert.ok(htfRule.includes('requires independent confirmation from HTF structure and 5M execution'));
assert.equal(/current.*9:30-11:15 ET|current.*10:00-11:15 ET|current.*10:00-11:50 ET|current.*11:50-13:00 ET|current.*11:50-15:30 ET/i.test(htfRule), false);

console.log('Gemini HTF draw prompt safety verified.');
