import assert from 'node:assert/strict';
import {
  buildUnifiedPositiveHeldLocalPreviewPreentryAdversePathClassifierReport,
} from './unified-positive-held-local-preview-preentry-adverse-path-classifier';
import type {
  UnifiedPositiveHeldLocalPreviewBroadProofContextEnrichmentReport,
} from './unified-positive-held-local-preview-broad-proof-context-enrichment';

const enrichmentReport: UnifiedPositiveHeldLocalPreviewBroadProofContextEnrichmentReport = {
  reportType: 'unified_positive_held_local_preview_broad_proof_context_enrichment',
  generatedAt: '2026-07-17T00:00:00.000Z',
  status: 'pass',
  authority: {
    readOnly: true,
    localOnly: true,
    researchOnly: true,
    postsDiscord: false,
    writesSupabase: false,
    readsLiveSupabase: false,
    readsLiveBridge: false,
    runsSetupScanner: false,
    changesScannerBehavior: false,
    changesTradingLogic: false,
    changesCanExecute: false,
    changesEntryStopTargets: false,
    changesRiskRules: false,
    changesBridgeBehavior: false,
    changesDiscordPosting: false,
    changesAppRuntime: false,
  },
  source: {
    reportDir: 'diagnostic-reports',
    broadRiskCapValidationPath: 'broad.json',
    intakeTriagePath: 'triage.json',
    auditDir: 'discord-audit',
  },
  assumptions: {
    usesCompletedFiveMinuteTapesOnly: true,
    enrichmentIsResearchOnly: true,
    missingBarsAreNotInvented: true,
    unresolvedRowsAreNotWinsOrLosses: true,
    staleEntryThresholdMinutes: 30,
    livePromotionAllowed: false,
  },
  summary: {
    sourceRows: 6,
    enrichedRows: 6,
    blockedRows: 0,
    winners: 3,
    losses: 2,
    unresolved: 1,
    grossResolvedOneMesPl: 240,
    groupSummaries: 1,
    livePromotionAllowedRows: 0,
  },
  groups: [],
  rows: [
    {
      rowId: 'win-1',
      tradeDate: '2026-06-17',
      session: 'morning',
      setupType: 'NoInstalledSetup',
      direction: 'LONG',
      proofState: 'human_review_ready',
      riskQuality: 'tight',
      occurrences: 20,
      triageDecision: 'held_for_later_batch',
      outcomeBucket: 'winner',
      outcomeLabel: 't1_and_t2_hit',
      resolvedOneMesPl: 100,
      riskPoints: 6,
      proofTime: '2026-06-17T09:30:00',
      entryHitTime: '2026-06-17T09:35:00',
      proofToEntryMinutes: 5,
      sourceFile: 'tape.json',
      completedBarsAfterProof: 3,
      mfePoints: 12,
      maePoints: 2,
      mfeR: 2,
      maeR: 0.33,
      issueTags: ['winner'],
      blockers: [],
    },
    {
      rowId: 'win-2',
      tradeDate: '2026-06-18',
      session: 'morning',
      setupType: 'NoInstalledSetup',
      direction: 'LONG',
      proofState: 'human_review_ready',
      riskQuality: 'tight',
      occurrences: 18,
      triageDecision: 'held_for_later_batch',
      outcomeBucket: 'winner',
      outcomeLabel: 't1_and_t2_hit',
      resolvedOneMesPl: 100,
      riskPoints: 6,
      proofTime: '2026-06-18T09:30:00',
      entryHitTime: '2026-06-18T09:35:00',
      proofToEntryMinutes: 5,
      sourceFile: 'tape.json',
      completedBarsAfterProof: 3,
      mfePoints: 12,
      maePoints: 2,
      mfeR: 2,
      maeR: 0.33,
      issueTags: ['winner'],
      blockers: [],
    },
    {
      rowId: 'win-3',
      tradeDate: '2026-06-19',
      session: 'morning',
      setupType: 'NoInstalledSetup',
      direction: 'SHORT',
      proofState: 'human_review_ready',
      riskQuality: 'tight',
      occurrences: 16,
      triageDecision: 'held_for_later_batch',
      outcomeBucket: 'winner',
      outcomeLabel: 't1_and_t2_hit',
      resolvedOneMesPl: 100,
      riskPoints: 6,
      proofTime: '2026-06-19T09:30:00',
      entryHitTime: '2026-06-19T09:35:00',
      proofToEntryMinutes: 5,
      sourceFile: 'tape.json',
      completedBarsAfterProof: 3,
      mfePoints: 12,
      maePoints: 2,
      mfeR: 2,
      maeR: 0.33,
      issueTags: ['winner'],
      blockers: [],
    },
    {
      rowId: 'loss-1',
      tradeDate: '2026-06-20',
      session: 'lunch',
      setupType: 'NoInstalledSetup',
      direction: 'LONG',
      proofState: 'human_review_ready',
      riskQuality: 'normal',
      occurrences: 2,
      triageDecision: 'held_for_later_batch',
      outcomeBucket: 'loss',
      outcomeLabel: 'stopped_before_t1',
      resolvedOneMesPl: -30,
      riskPoints: 6,
      proofTime: '2026-06-20T12:30:00',
      entryHitTime: '2026-06-20T12:50:00',
      proofToEntryMinutes: 20,
      sourceFile: 'tape.json',
      completedBarsAfterProof: 3,
      mfePoints: 3,
      maePoints: 8,
      mfeR: 0.5,
      maeR: 1.33,
      issueTags: ['stopped_before_t1'],
      blockers: [],
    },
    {
      rowId: 'loss-2',
      tradeDate: '2026-06-21',
      session: 'lunch',
      setupType: 'NoInstalledSetup',
      direction: 'SHORT',
      proofState: 'human_review_ready',
      riskQuality: 'normal',
      occurrences: 2,
      triageDecision: 'held_for_later_batch',
      outcomeBucket: 'loss',
      outcomeLabel: 'stopped_before_t1',
      resolvedOneMesPl: -30,
      riskPoints: 6,
      proofTime: '2026-06-21T12:30:00',
      entryHitTime: '2026-06-21T12:50:00',
      proofToEntryMinutes: 20,
      sourceFile: 'tape.json',
      completedBarsAfterProof: 3,
      mfePoints: 3,
      maePoints: 8,
      mfeR: 0.5,
      maeR: 1.33,
      issueTags: ['stopped_before_t1'],
      blockers: [],
    },
    {
      rowId: 'unresolved',
      tradeDate: '2026-06-22',
      session: 'lunch',
      setupType: 'NoInstalledSetup',
      direction: 'LONG',
      proofState: 'human_review_ready',
      riskQuality: 'normal',
      occurrences: 1,
      triageDecision: 'held_for_later_batch',
      outcomeBucket: 'unresolved',
      outcomeLabel: 'no_fill',
      resolvedOneMesPl: null,
      riskPoints: 6,
      proofTime: '2026-06-22T12:30:00',
      entryHitTime: null,
      proofToEntryMinutes: null,
      sourceFile: 'tape.json',
      completedBarsAfterProof: 3,
      mfePoints: null,
      maePoints: null,
      mfeR: null,
      maeR: null,
      issueTags: ['no_fill'],
      blockers: [],
    },
  ],
  blockers: [],
  recommendations: [],
  markdown: '',
};

const report = buildUnifiedPositiveHeldLocalPreviewPreentryAdversePathClassifierReport({
  reportDir: 'diagnostic-reports',
  proofContextEnrichmentPath: 'enrichment.json',
  proofContextEnrichmentReport: enrichmentReport,
}, '2026-07-17T00:01:00.000Z');

assert.equal(report.reportType, 'unified_positive_held_local_preview_preentry_adverse_path_classifier');
assert.equal(report.status, 'pass');
assert.equal(report.authority.readOnly, true);
assert.equal(report.authority.writesSupabase, false);
assert.equal(report.authority.postsDiscord, false);
assert.equal(report.authority.changesTradingLogic, false);
assert.equal(report.assumptions.excludesMfeMaeAndOutcomePathFromFeatures, true);
assert.equal(report.summary.sourceRows, 6);
assert.ok(report.summary.acceptedClassifiers >= 1);
assert.equal(report.summary.livePromotionAllowedRows, 0);

const top = report.classifiers[0];
assert.equal(top.decision, 'candidate_for_more_research');
assert.equal(top.falseRejectWinnerRows, 0);
assert.equal(top.keptWinners, 3);
assert.equal(top.keptLosses, 0);
assert.match(report.markdown, /Pre-Entry Adverse-Path Classifier/);

const missing = buildUnifiedPositiveHeldLocalPreviewPreentryAdversePathClassifierReport({
  reportDir: 'diagnostic-reports',
  proofContextEnrichmentPath: null,
  proofContextEnrichmentReport: null,
}, '2026-07-17T00:02:00.000Z');

assert.equal(missing.status, 'fail');
assert.ok(missing.blockers.includes('missing proof/context enrichment path'));

console.log('unified positive held-local pre-entry adverse-path classifier verified.');
