import assert from 'node:assert/strict';
import {
  buildUnifiedPositiveHeldLocalPreviewReplacementBlockerDrilldownReport,
} from './unified-positive-held-local-preview-replacement-blocker-drilldown';
import type {
  UnifiedPositiveHeldLocalPreviewReplayPackageOutcomeReport,
} from './unified-positive-held-local-preview-replay-package-outcome';
import type {
  UnifiedPositiveHeldLocalPreviewReplayPackageSourceProofTimingReport,
} from './unified-positive-held-local-preview-replay-package-source-proof-timing';
import type {
  UnifiedPositiveHeldLocalPreviewSweepPenaltyInstalledScoreComparisonReport,
} from './unified-positive-held-local-preview-sweep-penalty-installed-score-comparison';
import type {
  UnifiedPositiveHeldLocalPreviewraidReclaimExtremeRiskCompanionFilterReport,
} from './unified-positive-held-local-preview-raidReclaim-extreme-risk-companion-filter';

const authority = {
  readOnly: true,
  localOnly: true,
  researchOnly: true,
  postsDiscord: false,
  writesSupabase: false,
  readsLiveSupabase: false,
  readsLiveBridge: false,
  runsSetupScanner: false,
  changesScannerBehavior: false,
  changesTradingLogic: false,
  changesCanExecute: false,
  changesEntryStopTargets: false,
  changesRiskRules: false,
  changesBridgeBehavior: false,
  changesDiscordPosting: false,
  changesAppRuntime: false,
} as const;

const companion = {
  reportType: 'unified_positive_held_local_preview_raidReclaim_extreme_risk_companion_filter',
  generatedAt: '2026-07-18T00:00:00.000Z',
  status: 'pass',
  authority,
  source: {
    reportDir: 'reports',
    installedScoreComparisonPath: 'installed.json',
    sourceProofTimingPath: 'timing.json',
    extremeRiskSimulationPath: 'extreme.json',
  },
  assumptions: {
    researchOnly: true,
    variantsUsePreEntryFieldsOnly: true,
    outcomeUsedForEvaluationOnly: true,
    replacementMustRemainValidReview: true,
    noLiveFilterInstalled: true,
    livePromotionAllowed: false,
  },
  summary: {
    installedRows: 2,
    joinedRows: 2,
    variants: 1,
    candidateVariants: 0,
    rejectedBlockedReplacementVariants: 1,
    livePromotionAllowedRows: 0,
    recommendation: 'do_not_install_extreme_risk_penalty',
  },
  variants: [],
  changedSlates: [
    {
      variantId: 'risk_gt_20',
      slateId: '2026-06-10|lunch',
      topBeforeTicketId: 'before',
      topBeforeSetupType: 'raidReclaim',
      topBeforeOutcomeBucket: 'loss_stopped_before_t1',
      topBeforeOneMesPl: -100,
      topAfterTicketId: 'bad-long',
      topAfterSetupType: 'SweepMssFvgRetrace',
      topAfterOutcomeBucket: 'blocked',
      topAfterOneMesPl: null,
      topAfterValidReview: false,
    },
    {
      variantId: 'risk_gt_15',
      slateId: '2026-06-05|lunch',
      topBeforeTicketId: 'before-winner',
      topBeforeSetupType: 'raidReclaim',
      topBeforeOutcomeBucket: 'winner_t1_t2',
      topBeforeOneMesPl: 150,
      topAfterTicketId: 'clean-short',
      topAfterSetupType: 'SweepMssFvgRetrace',
      topAfterOutcomeBucket: 'winner_t1_t2',
      topAfterOneMesPl: 200,
      topAfterValidReview: true,
    },
  ],
  blockers: [],
  recommendations: [],
  markdown: '',
} satisfies UnifiedPositiveHeldLocalPreviewraidReclaimExtremeRiskCompanionFilterReport;

const installed: UnifiedPositiveHeldLocalPreviewSweepPenaltyInstalledScoreComparisonReport = {
  reportType: 'unified_positive_held_local_preview_sweep_penalty_installed_score_comparison',
  generatedAt: '2026-07-18T00:00:00.000Z',
  status: 'pass',
  authority,
  source: {
    reportDir: 'reports',
    sourceProofTimingPath: 'timing.json',
    intakeTriagePath: 'intake.json',
    freshScannerOverlayDryRunPath: 'overlay.json',
  },
  summary: {
    sourceRows: 2,
    joinedRows: 2,
    candidateBookRows: 2,
    sweepRows: 2,
    validSweepLeadRows: 2,
    invalidStopSweepPenaltyRows: 0,
    installedPenaltyRows: 0,
    validSweepLeadRowsPenalized: 0,
    canExecuteTrueRows: 0,
    entryStopTargetRiskDriftRows: 0,
    overlayTopSelectionDeltaOneMesPl: 0,
    overlayMatchesExpectedRows: true,
    recommendation: 'installed_score_path_matches_research_overlay',
    livePromotionAllowedRows: 0,
  },
  rows: [
    {
      ticketId: 'bad-long',
      tradeDate: '2026-06-10',
      session: 'lunch',
      setupType: 'SweepMssFvgRetrace',
      direction: 'LONG',
      executionStatus: 'Conditional',
      blockReason: 'EntryTriggerPending',
      installedScore: 84,
      candidateBookState: 'watch',
      validSweepLead: true,
      invalidStopSweepPenaltyCandidate: false,
      installedPenaltyExpected: false,
      canExecute: false,
      entryPreserved: true,
      stopPreserved: true,
      target1Preserved: true,
      target2Preserved: true,
      riskPreserved: true,
    },
    {
      ticketId: 'clean-short',
      tradeDate: '2026-06-05',
      session: 'lunch',
      setupType: 'SweepMssFvgRetrace',
      direction: 'SHORT',
      executionStatus: 'Conditional',
      blockReason: 'EntryTriggerPending',
      installedScore: 82,
      candidateBookState: 'human_review',
      validSweepLead: true,
      invalidStopSweepPenaltyCandidate: false,
      installedPenaltyExpected: false,
      canExecute: false,
      entryPreserved: true,
      stopPreserved: true,
      target1Preserved: true,
      target2Preserved: true,
      riskPreserved: true,
    },
  ],
  blockers: [],
  recommendations: [],
  markdown: '',
};

const timing: UnifiedPositiveHeldLocalPreviewReplayPackageSourceProofTimingReport = {
  reportType: 'unified_positive_held_local_preview_replay_package_source_proof_timing',
  generatedAt: '2026-07-18T00:00:00.000Z',
  status: 'pass',
  authority,
  source: {
    reportDir: 'reports',
    replayPackageOutcomePath: 'outcome.json',
  },
  assumptions: {
    usesReadOnlyOutcomeReportOnly: true,
    fullDeliveryWinnerMeansT1AndT2Hit: true,
    stoppedBeforeT1MeansTimingLoss: true,
    unresolvedRowsAreNotWinsOrLosses: true,
    staleEntryThresholdMinutes: 30,
    livePromotionAllowed: false,
  },
  summary: {
    evaluatedRows: 2,
    winners: 1,
    losses: 0,
    unresolved: 0,
    blocked: 1,
    grossResolvedOneMesPl: 200,
    positiveModelGroups: 1,
    negativeModelGroups: 0,
    unresolvedModelGroups: 0,
    livePromotionAllowedRows: 0,
  },
  modelTiming: [],
  rows: [
    {
      ticketId: 'bad-long',
      tradeDate: '2026-06-10',
      session: 'lunch',
      setupType: 'SweepMssFvgRetrace',
      direction: 'LONG',
      outcomeBucket: 'blocked',
      outcomeLabel: 'blocked',
      resolvedOneMesPl: null,
      proofTime: '2026-06-10T13:50:00',
      entryHitTime: null,
      proofToEntryMinutes: null,
      riskPoints: 31.25,
      mfeR: null,
      maeR: null,
      issueTags: [],
    },
    {
      ticketId: 'clean-short',
      tradeDate: '2026-06-05',
      session: 'lunch',
      setupType: 'SweepMssFvgRetrace',
      direction: 'SHORT',
      outcomeBucket: 'winner_t1_t2',
      outcomeLabel: 't1_and_t2_hit',
      resolvedOneMesPl: 200,
      proofTime: '2026-06-05T13:00:00',
      entryHitTime: '2026-06-05T13:05:00',
      proofToEntryMinutes: 5,
      riskPoints: 8,
      mfeR: 2,
      maeR: 0.2,
      issueTags: [],
    },
  ],
  blockers: [],
  recommendations: [],
  markdown: '',
};

const outcome = {
  reportType: 'unified_positive_held_local_preview_replay_package_outcome',
  generatedAt: '2026-07-18T00:00:00.000Z',
  status: 'pass',
  authority,
  source: {
    reportDir: 'reports',
    replayPackagePath: 'package.json',
  },
  assumptions: {
    oneMesPointValue: 5,
    usesCompletedFiveMinuteBarsOnly: true,
    missingBarsAreNotInvented: true,
    sameBarStopAndTargetUsesConservativeStopFirst: true,
    outcomeIsResearchOnly: true,
    livePromotionAllowed: false,
  },
  summary: {
    packageRows: 2,
    resolvedRows: 1,
    unresolvedRows: 0,
    blockedRows: 1,
    grossResolvedOneMesPl: 200,
    noFillRows: 0,
    stoppedBeforeT1Rows: 0,
    t1OnlyRows: 0,
    t1AndT2Rows: 1,
    noTargetOrStopRows: 0,
    modelGroups: [],
    daySessionModelGroups: [],
    livePromotionAllowedRows: 0,
  },
  rows: [
    {
      ticketId: 'bad-long',
      tradeDate: '2026-06-10',
      session: 'lunch',
      setupType: 'SweepMssFvgRetrace',
      direction: 'LONG',
      proofTime: '2026-06-10T13:50:00',
      outcomeStatus: 'blocked',
      outcomeLabel: 'blocked',
      entry: 7308.25,
      stop: 7339.5,
      t1: 7355.25,
      t2: 7370.75,
      riskPoints: 31.25,
      barsSource: 'scanner_decision_tape_completed_5m',
      barsLoaded: 42,
      barsAfterProof: 20,
      entryHitTime: null,
      firstReplayBarTime: null,
      stopHitTime: null,
      t1HitTime: null,
      t2HitTime: null,
      maximumFavorableExcursion: null,
      maximumAdverseExcursion: null,
      resolvedOneMesPl: null,
      resolvedR: null,
      intrabarAmbiguity: false,
      blockers: ['directionally invalid entry-to-stop geometry'],
    },
    {
      ticketId: 'clean-short',
      tradeDate: '2026-06-05',
      session: 'lunch',
      setupType: 'SweepMssFvgRetrace',
      direction: 'SHORT',
      proofTime: '2026-06-05T13:00:00',
      outcomeStatus: 'resolved',
      outcomeLabel: 't1_and_t2_hit',
      entry: 7400,
      stop: 7408,
      t1: 7388,
      t2: 7384,
      riskPoints: 8,
      barsSource: 'scanner_decision_tape_completed_5m',
      barsLoaded: 42,
      barsAfterProof: 20,
      entryHitTime: '2026-06-05T13:05:00',
      firstReplayBarTime: '2026-06-05T13:05:00',
      stopHitTime: null,
      t1HitTime: '2026-06-05T13:10:00',
      t2HitTime: '2026-06-05T13:15:00',
      maximumFavorableExcursion: 16,
      maximumAdverseExcursion: 1,
      resolvedOneMesPl: 200,
      resolvedR: 2,
      intrabarAmbiguity: false,
      blockers: [],
    },
  ],
  blockers: [],
  recommendations: [],
  markdown: '',
} satisfies UnifiedPositiveHeldLocalPreviewReplayPackageOutcomeReport;

const report = buildUnifiedPositiveHeldLocalPreviewReplacementBlockerDrilldownReport({
  reportDir: 'reports',
  companionFilterPath: 'companion.json',
  companionFilterReport: companion,
  installedScoreComparisonPath: 'installed.json',
  installedScoreComparisonReport: installed,
  sourceProofTimingPath: 'timing.json',
  sourceProofTimingReport: timing,
  replayPackageOutcomePath: 'outcome.json',
  replayPackageOutcomeReport: outcome,
}, '2026-07-18T00:00:00.000Z');

assert.equal(report.status, 'pass');
assert.equal(report.summary.changedSlateReplacementRows, 2);
assert.equal(report.summary.directionallyInvalidGeometryRows, 1);
assert.equal(report.summary.viableReplacementRows, 1);
assert.equal(report.summary.livePromotionAllowedRows, 0);
assert.equal(report.summary.recommendation, 'fix_replacement_geometry_source_before_rank_changes');
assert.equal(report.rows.find((row) => row.ticketId === 'bad-long')?.failureClass, 'directionally_invalid_entry_stop_geometry');
assert.equal(report.rows.find((row) => row.ticketId === 'clean-short')?.failureClass, 'viable_replacement');
assert.equal(report.authority.postsDiscord, false);
assert.equal(report.authority.writesSupabase, false);
assert.equal(report.authority.changesCanExecute, false);
assert.equal(report.authority.changesEntryStopTargets, false);

const blocked = buildUnifiedPositiveHeldLocalPreviewReplacementBlockerDrilldownReport({
  reportDir: 'reports',
  companionFilterPath: null,
  companionFilterReport: null,
  installedScoreComparisonPath: 'installed.json',
  installedScoreComparisonReport: installed,
  sourceProofTimingPath: 'timing.json',
  sourceProofTimingReport: timing,
  replayPackageOutcomePath: 'outcome.json',
  replayPackageOutcomeReport: outcome,
}, '2026-07-18T00:01:00.000Z');

assert.equal(blocked.status, 'fail');
assert.equal(blocked.summary.recommendation, 'reject_missing_source');
assert.ok(blocked.blockers.some((item) => item.includes('missing companion-filter path')));

console.log('unified positive held-local replacement blocker drilldown verified.');
