import { SetupType } from '../types';

export type SetupSession = 'morning' | 'lunch' | 'evening' | 'replay_morning' | 'replay_lunch';
export type SetupRole = 'primary_model' | 'supporting_evidence' | 'deprecated';
export type ParentModelFamily =
  | 'MODEL_1_SWEEP_MSS_FVG_RETRACE'
  | 'FAILED_BREAKOUT_REVERSAL'
  | 'HTF_DISPLACEMENT_CONTINUATION'
  | 'FAILED_PLAN_REVERSAL';

export interface SetupRegistryEntry {
  setupType: SetupType;
  role: SetupRole;
  parentModelFamily?: ParentModelFamily;
  label: string;
  aliases: string[];
  priority: number;
  allowedSessions: SetupSession[];
  detectionKeywords: string[];
  possibleKeywords: string[];
  requiredEvidence: string[];
  defaultRequiredTrigger: string;
  defaultNextAction: string;
}

const BOTH_SESSIONS: SetupSession[] = ['morning', 'lunch', 'evening', 'replay_morning', 'replay_lunch'];
const MORNING_SESSIONS: SetupSession[] = ['morning', 'replay_morning'];
const LUNCH_SESSIONS: SetupSession[] = ['lunch', 'replay_lunch'];

// Registry roles are metadata only in this phase. Later phases should let
// primary_model entries create active trade candidates, supporting_evidence
// entries contribute facts/reasons/scoring only, and deprecated entries stay
// out of active scanner, Discord alert, and trade-decision logic.
export const SETUP_REGISTRY: SetupRegistryEntry[] = [
  {
    setupType: SetupType.OrderBlock618,
    role: 'deprecated',
    label: 'Prior Impulse Reaction Zone / 61.8%',
    aliases: ['61.8 Golden Ratio', 'Risk Mitigation Order Block'],
    priority: 82,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['61.8', 'golden ratio', 'order block', 'retracement'],
    possibleKeywords: ['pullback', 'mitigation', 'block'],
    requiredEvidence: ['Opening range high/low', 'Retracement level', 'Protected block extreme'],
    defaultRequiredTrigger: 'Limit or reclaim trigger at the 61.8% retracement with stop outside structure.',
    defaultNextAction: 'Confirm the retracement level and stop distance before execution.',
  },
  {
    setupType: SetupType.SweepMssFvgRetrace,
    role: 'primary_model',
    parentModelFamily: 'MODEL_1_SWEEP_MSS_FVG_RETRACE',
    label: 'Sweep -> MSS -> FVG Retrace',
    aliases: ['Sweep Reclaim Imbalance Retrace', 'Sweep MSS FVG', 'Model 1'],
    priority: 98,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['sweep mss fvg', 'sweep reclaim displacement structure shift fvg retrace', 'sweep reclaim imbalance retrace'],
    possibleKeywords: ['liquidity sweep', 'reclaim', 'market structure shift', 'fvg retrace', 'imbalance retrace'],
    requiredEvidence: ['Liquidity sweep', 'Reclaim after sweep', 'Displacement', 'Market structure shift', 'FVG retrace', 'Clean 1.5R path'],
    defaultRequiredTrigger: 'Retrace into the FVG after sweep, reclaim, displacement, and market structure shift are confirmed.',
    defaultNextAction: 'Wait for the FVG retrace and structure-based stop; do not chase the displacement candle.',
  },
  {
    setupType: SetupType.LiquiditySweep,
    role: 'supporting_evidence',
    label: 'Liquidity Sweep',
    aliases: ['Sweep and Reclaim', 'Stop Hunt'],
    priority: 96,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['liquidity sweep', 'sweep', 'stop hunt', 'reclaim', 'wick breach'],
    possibleKeywords: ['liquidity', 'trap', 'wick', 'failed break'],
    requiredEvidence: ['Swept level', 'Reclaim candle', 'Invalidation beyond sweep extreme'],
    defaultRequiredTrigger: 'Reclaim of swept level or break of reclaim candle in trade direction.',
    defaultNextAction: 'Wait for reclaim confirmation if the sweep has not closed back inside structure.',
  },
  {
    setupType: SetupType.TurtleSoup,
    role: 'primary_model',
    parentModelFamily: 'FAILED_BREAKOUT_REVERSAL',
    label: 'Turtle Soup Reversal',
    aliases: ['Turtle Soup', 'Failed Breakout Reversal', 'Failed Breakdown Reversal'],
    priority: 95,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['turtle soup', 'failed breakout reversal', 'failed breakdown reversal', 'sweep reclaim reversal'],
    possibleKeywords: ['liquidity raid reversal', 'failed continuation', 'reclaim after sweep', 'reversal after sweep'],
    requiredEvidence: ['Swept swing/session level', 'Reclaim back inside level', 'Stop beyond sweep wick', 'Clean path to app T1 at 1.5R; T2 is extension/management context'],
    defaultRequiredTrigger: 'Reclaim confirmation after the sweep, preferably followed by expansion or a structure shift.',
    defaultNextAction: 'Wait for reclaim confirmation or a retrace after expansion; do not chase the initial reversal move.',
  },
  {
    setupType: SetupType.MomentumRunaway,
    role: 'deprecated',
    label: 'Momentum / Runaway',
    aliases: ['Runaway', 'Momentum Entry'],
    priority: 88,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['momentum', 'runaway', 'vertical expansion', 'impulse continuation', 'stacked'],
    possibleKeywords: ['continuation', 'expansion', 'strong trend', 'trend continuation'],
    requiredEvidence: ['Directional candles', 'Minimal overlap', 'Prior candle break trigger'],
    defaultRequiredTrigger: 'Break of prior completed candle high/low in trend direction.',
    defaultNextAction: 'If immediate risk is too wide, wait for a breather/pullback reclaim.',
  },
  {
    setupType: SetupType.FairValueGap,
    role: 'supporting_evidence',
    label: 'Imbalance Zone',
    aliases: ['FVG', 'Imbalance'],
    priority: 86,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['fair value gap', 'fvg', 'imbalance'],
    possibleKeywords: ['gap', 'inefficiency', 'rebalance'],
    requiredEvidence: ['Three-candle imbalance', 'Gap boundary', 'Direction after displacement'],
    defaultRequiredTrigger: 'Reaction from the imbalance boundary or midpoint with stop beyond the imbalance structure.',
    defaultNextAction: 'Wait for price to trade into the imbalance zone.',
  },
  {
    setupType: SetupType.FvgImbalancePullback,
    role: 'supporting_evidence',
    label: 'Imbalance Pullback',
    aliases: ['FVG Pullback', 'Imbalance Rebalance'],
    priority: 84,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['fvg pullback', 'imbalance pullback', 'rebalance', 'gap fill continuation'],
    possibleKeywords: ['pullback into imbalance', 'return to fvg', 'return to imbalance'],
    requiredEvidence: ['Visible imbalance', 'Pullback into gap', 'Continuation trigger'],
    defaultRequiredTrigger: 'Pullback into the imbalance followed by a reclaim or candle break in trend direction.',
    defaultNextAction: 'Mark the imbalance zone and wait for a clean continuation trigger with a structure stop inside the allowed risk limit.',
  },
  {
    setupType: SetupType.MarketStructureShift,
    role: 'supporting_evidence',
    label: 'Market Structure Reversal',
    aliases: ['MSS', 'ChoCH', 'Change of Character'],
    priority: 80,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['market structure shift', 'mss', 'choch', 'change of character', 'structure shift'],
    possibleKeywords: ['break of structure', 'character change', 'shift'],
    requiredEvidence: ['Prior swing', 'Break or close beyond swing', 'Protected invalidation level'],
    defaultRequiredTrigger: 'Break or close beyond the confirming swing after the shift.',
    defaultNextAction: 'Wait for structural confirmation if only the first shift is visible.',
  },
  {
    setupType: SetupType.HtfDrawContinuationAfterRaid,
    role: 'primary_model',
    parentModelFamily: 'HTF_DISPLACEMENT_CONTINUATION',
    label: 'HTF Draw Continuation After Raid/Reclaim',
    aliases: ['HTF Draw Continuation', 'Raid Reclaim MSS Delivery', 'HTF Liquidity Draw Reversal Delivery'],
    priority: 97,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['htf draw continuation', 'raid reclaim mss delivery', 'htf liquidity draw reversal delivery'],
    possibleKeywords: ['htf draw', 'sell-side raid', 'buy-side raid', 'reclaim', '5m mss', 'external liquidity'],
    requiredEvidence: [
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      '4H/1H draw supports or does not materially conflict',
      '15M raid/reclaim confirmed, potential, or pending',
      'Confirmed 5M MSS with displacement',
      'External liquidity target',
      'App-owned entry, stop, target, risk, and invalidation gates',
    ],
    defaultRequiredTrigger: 'Confirmed 5M MSS after raid/reclaim, followed by the app-owned entry trigger and protected structure stop.',
    defaultNextAction: 'Final action only after the app-owned entry, stop, target, risk, invalidation, session, and canExecute gates remain confirmed.',
  },
  {
    setupType: SetupType.HtfDisplacementMssContinuation,
    role: 'primary_model',
    parentModelFamily: 'HTF_DISPLACEMENT_CONTINUATION',
    label: 'HTF Displacement + 5M MSS Continuation',
    aliases: ['HTF Displacement MSS Continuation', '15M Displacement 5M MSS Continuation', 'HTF Displacement Delivery'],
    priority: 96,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['htf displacement mss continuation', '15m displacement 5m mss', 'displacement mss continuation'],
    possibleKeywords: ['15m displacement', '5m mss', 'bearish displacement', 'bullish displacement', 'external liquidity continuation'],
    requiredEvidence: [
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      'Directional 15M displacement with acceptable body/close quality',
      '5M displacement or imbalance in the same direction',
      'Confirmed 5M MSS by completed candle close',
      'Defined 5M entry at or beyond the MSS close-through trigger',
      'Protected structure stop',
      'External liquidity target with at least 60% of the original path remaining',
    ],
    defaultRequiredTrigger: 'Confirmed 5M MSS close in the 15M displacement direction, then entry at or beyond the MSS close-through trigger with protected structure stop.',
    defaultNextAction: 'Review the structurally complete plan. Risk above the standard cap is advisory only and requires human final decision.',
  },
  {
    setupType: SetupType.HtfDisplacementFvgContinuation,
    role: 'primary_model',
    parentModelFamily: 'HTF_DISPLACEMENT_CONTINUATION',
    label: 'HTF Displacement + FVG Continuation',
    aliases: ['HTF Displacement FVG Continuation', '15M Displacement FVG Continuation', 'Displacement-Led Continuation'],
    priority: 94,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['htf displacement fvg continuation', '15m displacement fvg continuation', 'displacement-led continuation'],
    possibleKeywords: ['15m displacement', '5m fvg', '5m imbalance', 'bearish displacement continuation', 'bullish displacement continuation'],
    requiredEvidence: [
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      'Directional 15M displacement with acceptable body/close quality',
      '5M FVG / imbalance retest or support',
      'Defined 5M entry from retest, close-through, or MSS continuation close if present',
      'Protected structure stop',
      'External liquidity target with at least 60% of the original path remaining',
    ],
    defaultRequiredTrigger: 'Displacement-led 5M continuation trigger: clean FVG/imbalance retest, close-through continuation, or confirmed MSS continuation close if present.',
    defaultNextAction: 'Review the structurally complete displacement-led plan. Risk above the standard cap is advisory only and requires human final decision.',
  },
  {
    setupType: SetupType.OpeningDriveFvgContinuation,
    role: 'primary_model',
    parentModelFamily: 'HTF_DISPLACEMENT_CONTINUATION',
    label: 'Opening Drive FVG Continuation',
    aliases: ['Opening Drive FVG', '15M Opening Displacement 5M FVG', 'Opening Drive Continuation'],
    priority: 97,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['opening drive fvg continuation', '15m opening displacement 5m fvg', 'opening drive continuation'],
    possibleKeywords: ['15m displacement', '5m fvg retest', 'opening drive', 'bearish opening drive', 'bullish opening drive'],
    requiredEvidence: [
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      'Directional 15M opening displacement with acceptable body/close quality',
      'Completed 5M MSS or valid 5M displacement structure in the same direction',
      '5M FVG / imbalance formed by or immediately following the displacement leg',
      '5M FVG retest or mitigation during the 10:00-11:00 ET review window',
      'Defined 5M FVG retest entry or entry zone',
      'Protected 5M structure stop',
      'App-owned T1/T2 from actual entry-to-stop risk',
      'Forward liquidity/target context in the trade direction',
    ],
    defaultRequiredTrigger: 'Human-review only: 15M opening displacement plus aligned 5M MSS/displacement and a clean 5M FVG retest/mitigation during the review window.',
    defaultNextAction: 'Produce a full decision-support trade plan for human review only. Trader confirmation is required before action; canExecute remains false.',
  },
  {
    setupType: SetupType.AfterLunchDriveFvgContinuation,
    role: 'primary_model',
    parentModelFamily: 'HTF_DISPLACEMENT_CONTINUATION',
    label: 'After-Lunch Drive FVG Continuation',
    aliases: ['After-Lunch Drive FVG', 'Lunch Drive FVG', '12PM Drive Continuation', 'After Lunch Drive Continuation'],
    priority: 97,
    allowedSessions: LUNCH_SESSIONS,
    detectionKeywords: ['after-lunch drive fvg continuation', 'lunch drive fvg continuation', '12pm drive continuation', 'after lunch drive continuation'],
    possibleKeywords: ['15m lunch displacement', '5m fvg retest', 'after-lunch drive', 'lunch drive', 'bearish lunch drive', 'bullish lunch drive'],
    requiredEvidence: [
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      'Directional 15M after-lunch displacement with acceptable body/close quality',
      'Completed 5M MSS or valid 5M displacement structure in the same direction',
      '5M FVG / imbalance formed by or immediately following the after-lunch displacement leg',
      '5M FVG retest or mitigation during the 12:30-13:30 ET review window',
      'Defined 5M FVG retest entry or entry zone',
      'Protected 5M structure stop',
      'App-owned T1/T2 from actual entry-to-stop risk',
      'Forward liquidity/target context in the trade direction',
    ],
    defaultRequiredTrigger: 'Human-review only: 15M after-lunch displacement plus aligned 5M MSS/displacement and a clean 5M FVG retest/mitigation during the review window.',
    defaultNextAction: 'Produce a full decision-support trade plan for human review only. Trader confirmation is required before action; canExecute remains false.',
  },
  {
    setupType: SetupType.IntradayMssMicroContinuation,
    role: 'primary_model',
    parentModelFamily: 'HTF_DISPLACEMENT_CONTINUATION',
    label: 'Intraday MSS Micro Continuation',
    aliases: ['Intraday MSS Micro Continuation', '15M 5M MSS Micro Continuation', 'Micro Continuation Retest'],
    priority: 96,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['intraday mss micro continuation', '15m 5m mss micro continuation', 'micro continuation retest'],
    possibleKeywords: ['15m mss', '5m mss', '5m fvg retest', 'micro continuation', 'no chase'],
    requiredEvidence: [
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      '15M and 5M completed MSS aligned in the same direction',
      '5M FVG / imbalance in the MSS direction',
      'Completed 5M FVG retest/rejection or completed close-through beyond the named line in the sand',
      'Close-through activates the campaign; completed retest failure/hold creates the preferred 5M structure stop',
      'Protected 5M retest/FVG structure stop',
      'App-owned T1/T2 from actual entry-to-stop risk',
      'HTF obstacle map and line-in-the-sand caution when price is entering support/resistance',
    ],
    defaultRequiredTrigger: 'Human-review only: aligned completed 15M and 5M MSS. The completed 5M close-through activates the campaign; a completed retest failure/hold creates the preferred 5M structure stop.',
    defaultNextAction: 'No chase. Produce a micro-continuation plan for human review only after the completed 5M retest/rejection or post-close-through retest failure/hold confirms; canExecute remains false.',
  },
  {
    setupType: SetupType.FailedPlanReversal,
    role: 'primary_model',
    parentModelFamily: 'FAILED_PLAN_REVERSAL',
    label: 'Failed Plan Reversal',
    aliases: ['Failed Long Reversal', 'Failed Short Reversal', 'Opposite-Side Decision Level'],
    priority: 95,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['failed plan reversal', 'failed decision level', 'opposite-side decision level'],
    possibleKeywords: ['failed reclaim level', 'failed long', 'failed short', 'opposite mss', 'role flip'],
    requiredEvidence: [
      'App-owned plan failed its decision/reclaim level',
      'Full 30-day structured 4H/2H/1H/15M/5M HTF context gate satisfied',
      '15M confirms opposite MSS/displacement',
      '1H confirms opposite MSS/displacement',
      '2H confirms opposite structure',
      '4H confirms opposite structure',
      'Fresh completed 5M opposite-side MSS, retest, or defined reclaim trigger',
      'Defined 5M entry, protected structure stop, app targets, invalidation, and session gates',
    ],
    defaultRequiredTrigger: 'Failed plan level becomes the opposite-side decision level only after 15M, 1H, 2H, and 4H opposite structure confirmation, then a fresh completed 5M trigger/retest.',
    defaultNextAction: 'Treat as a new app-owned plan candidate only after fresh 5M trigger, protected stop, app targets, invalidation, and normal deterministic gates are present.',
  },
  {
    setupType: SetupType.OpeningOrderBlock,
    role: 'deprecated',
    label: 'Opening Reaction Zone',
    aliases: ['Confirmation Bar', 'Opening Confirmation Bar'],
    priority: 78,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['opening order block', 'confirmation bar', 'opening block'],
    possibleKeywords: ['opening range', 'confirmation', '9:35'],
    requiredEvidence: ['9:30-9:35 range', 'Confirmation candle', 'Block extreme'],
    defaultRequiredTrigger: 'Entry at the approved retracement or break from the opening block.',
    defaultNextAction: 'Confirm opening block boundaries and risk before execution.',
  },
  {
    setupType: SetupType.EqualHighsLows,
    role: 'supporting_evidence',
    label: 'Resting Liquidity Pool',
    aliases: ['EQH', 'EQL', 'Liquidity Pool'],
    priority: 76,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['equal highs', 'equal lows', 'eqh', 'eql', 'liquidity pool'],
    possibleKeywords: ['resting liquidity', 'double top', 'double bottom'],
    requiredEvidence: ['Two or more equal levels', 'Sweep or reaction', 'Invalidation beyond pool'],
    defaultRequiredTrigger: 'Sweep and reclaim of equal highs/lows or continuation through the pool.',
    defaultNextAction: 'Wait for sweep/reclaim or clean continuation through the pool.',
  },
  {
    setupType: SetupType.InitialBalanceExtension,
    role: 'deprecated',
    label: 'Opening Range Extension',
    aliases: ['IB Extension'],
    priority: 74,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['initial balance extension', 'ib extension', 'ib high', 'ib low'],
    possibleKeywords: ['initial balance', 'ib range', 'range extension'],
    requiredEvidence: ['IB high', 'IB low', 'Break/retest or failed break'],
    defaultRequiredTrigger: 'Break and retest of IB high/low or rejection back into the IB range.',
    defaultNextAction: 'Confirm whether price is extending from or fading back into the IB.',
  },
  {
    setupType: SetupType.PreviousDaySweep,
    role: 'supporting_evidence',
    label: 'Previous Day High/Low Sweep',
    aliases: ['PDH Sweep', 'PDL Sweep'],
    priority: 72,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['previous day sweep', 'pdh', 'pdl', 'prior day high', 'prior day low'],
    possibleKeywords: ['previous day', 'prior day', 'daily high', 'daily low'],
    requiredEvidence: ['Prior day level', 'Sweep/reclaim or failure', 'Directional trigger'],
    defaultRequiredTrigger: 'Sweep and reclaim of PDH/PDL or failed reclaim continuation.',
    defaultNextAction: 'Confirm the prior day level and whether price reclaimed or rejected it.',
  },
  {
    setupType: SetupType.CompressionBreakout,
    role: 'deprecated',
    label: 'Compression Breakout',
    aliases: ['Coil', 'Spring'],
    priority: 68,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['compression breakout', 'compression', 'coil', 'spring', 'tight range'],
    possibleKeywords: ['consolidation', 'range contraction', 'breakout'],
    requiredEvidence: ['Compressed range', 'Breakout side', 'Opposite range boundary stop'],
    defaultRequiredTrigger: 'Break of the compression range high/low with stop beyond the opposite side.',
    defaultNextAction: 'Wait for the range break if compression is still forming.',
  },
  {
    setupType: SetupType.OpeningGapFill,
    role: 'deprecated',
    label: 'Opening Gap Fill',
    aliases: ['Gap Fill'],
    priority: 66,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['opening gap fill', 'gap fill', 'prior close', 'previous close'],
    possibleKeywords: ['gap', 'open gap', 'fill'],
    requiredEvidence: ['RTH open', 'Prior close', 'Gap direction and fill target'],
    defaultRequiredTrigger: 'Pullback or rejection that confirms the gap-fill direction.',
    defaultNextAction: 'Confirm prior close and whether the open is filling or going with the gap.',
  },
  {
    setupType: SetupType.BreakerBlock,
    role: 'supporting_evidence',
    label: 'Failed Structure Retest Zone',
    aliases: ['Breaker'],
    priority: 62,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['breaker block', 'breaker'],
    possibleKeywords: ['violated order block', 'broken block'],
    requiredEvidence: ['Violated block', 'Displacement break', 'Retest zone'],
    defaultRequiredTrigger: 'Retest of the failed structure zone with directional rejection.',
    defaultNextAction: 'Wait for a retest and rejection from the violated block.',
  },
  {
    setupType: SetupType.AlgoKillZone,
    role: 'deprecated',
    label: 'Execution Window Setup',
    aliases: ['Kill Zone', 'Time Mechanics'],
    priority: 90,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['algo kill zone', 'kill zone', 'macro window', 'time window'],
    possibleKeywords: ['active setup scan', 'execution window', 'time-based'],
    requiredEvidence: ['Active execution window', 'Sweep or structure shift inside window', 'Directional trigger'],
    defaultRequiredTrigger: 'Sweep plus structure shift inside the active time window.',
    defaultNextAction: 'Confirm that price action, not time alone, gives the trigger.',
  },
  {
    setupType: SetupType.MitigationBlock,
    role: 'deprecated',
    label: 'Initiating Move Retest Zone',
    aliases: ['Mitigation'],
    priority: 60,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['mitigation block', 'mitigation'],
    possibleKeywords: ['return to initiating candle', 'mitigate'],
    requiredEvidence: ['Initiating reversal candle', 'Return to candle range', 'Reaction trigger'],
    defaultRequiredTrigger: 'Return into the initiating move retest zone followed by rejection or reclaim.',
    defaultNextAction: 'Wait for price to return to the initiating candle range.',
  },
  {
    setupType: SetupType.MomentumPullbackBreatherReclaim,
    role: 'deprecated',
    label: 'Momentum Pullback / Breather Reclaim',
    aliases: ['Breather Reclaim', 'Momentum Pullback'],
    priority: 87,
    allowedSessions: BOTH_SESSIONS,
    detectionKeywords: ['momentum pullback', 'breather reclaim', 'breather pullback', 'pullback reclaim'],
    possibleKeywords: ['breather', 'pullback', 'reclaim after pullback'],
    requiredEvidence: ['Prior momentum leg', 'Completed pullback candle', 'Break/reclaim trigger'],
    defaultRequiredTrigger: 'Break of the completed pullback candle in the original trend direction.',
    defaultNextAction: 'Wait for the pullback candle to complete and break in trend direction.',
  },
  {
    setupType: SetupType.MorningFailedHighLiquidityRejection,
    role: 'deprecated',
    label: 'Morning Failed High / Liquidity Rejection',
    aliases: ['Morning Failed High', 'Failed High Liquidity Rejection', 'Morning Liquidity Rejection'],
    priority: 89,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['morning failed high', 'failed high', 'liquidity rejection', 'failed hold above key level'],
    possibleKeywords: ['rejection above resistance', 'failed hold', 'breakdown below reclaim area', 'sweep high'],
    requiredEvidence: ['Key resistance or failed high zone', 'Rejection or failed hold', 'Breakdown trigger below reclaim/support area', 'Stop above failed high/swing high'],
    defaultRequiredTrigger: '5M close below the reclaim/support area after failed hold above the key high.',
    defaultNextAction: 'Wait for the breakdown trigger; do not short until price confirms below support/reclaim.',
  },
  {
    setupType: SetupType.MorningReclaimLong,
    role: 'deprecated',
    label: 'Morning Reclaim Long',
    aliases: ['Morning Reclaim', 'Key Level Reclaim Long', 'Resistance Reclaim Long'],
    priority: 88,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['morning reclaim long', 'reclaim long', 'reclaim above key level', 'hold above resistance'],
    possibleKeywords: ['reclaim', 'hold above', 'pullback holds', 'break back above'],
    requiredEvidence: ['Key reclaim level', 'Close or hold above level', 'Pullback low for stop', 'Continuation trigger above reclaim'],
    defaultRequiredTrigger: '5M close above the key reclaim level, then pullback holds above it.',
    defaultNextAction: 'Wait for reclaim and pullback-hold confirmation before planning the long.',
  },
  {
    setupType: SetupType.MorningOpeningRangeContinuation,
    role: 'deprecated',
    label: 'Opening Range Continuation',
    aliases: ['Opening Range Continuation', 'Opening Range Retest', 'Opening Range Reclaim'],
    priority: 87,
    allowedSessions: MORNING_SESSIONS,
    detectionKeywords: ['opening range continuation', 'opening range break', 'opening range retest', 'opening range reclaim'],
    possibleKeywords: ['opening range', 'range break', 'retest holds', 'continuation trigger'],
    requiredEvidence: ['Opening range high/low', 'Expansion break from the opening range', 'Retest or reclaim of broken boundary', 'Structure stop beyond retest failure'],
    defaultRequiredTrigger: '5M close beyond the opening range, then retest/reclaim holds before continuation.',
    defaultNextAction: 'Preferred plan: trade the opening range retest/reclaim, not the breakout chase.',
  },
  {
    setupType: SetupType.LunchFailedHighReversal,
    role: 'deprecated',
    label: 'Lunch Failed High Reversal',
    aliases: ['Failed High Reversal', 'Morning High Failure', 'Lunch High Sweep Failure'],
    priority: 94,
    allowedSessions: LUNCH_SESSIONS,
    detectionKeywords: ['lunch failed high reversal', 'morning high sweep', 'failed hold above morning high', 'failed continuation short'],
    possibleKeywords: ['morning high', 'failed high', 'sweep above high', 'failed continuation'],
    requiredEvidence: ['Completed Morning window context', 'Morning high identified', 'Sweep above morning high', 'Failure to hold above morning high', '5M close back below or failed retest from below'],
    defaultRequiredTrigger: '5M close back below morning high or failed retest from below with stop 1 tick above sweep high.',
    defaultNextAction: 'Wait for the morning high sweep failure to confirm on the Lunch 5M execution chart.',
  },
  {
    setupType: SetupType.LunchFailedLowReversal,
    role: 'deprecated',
    label: 'Lunch Failed Low Reversal',
    aliases: ['Failed Low Reversal', 'Morning Low Failure', 'Lunch Low Sweep Failure'],
    priority: 94,
    allowedSessions: LUNCH_SESSIONS,
    detectionKeywords: ['lunch failed low reversal', 'morning low sweep', 'failed hold below morning low', 'failed continuation long'],
    possibleKeywords: ['morning low', 'failed low', 'sweep below low', 'failed breakdown'],
    requiredEvidence: ['Completed Morning window context', 'Morning low identified', 'Sweep below morning low', 'Failure to hold below morning low', '5M close back above or failed retest from above'],
    defaultRequiredTrigger: '5M close back above morning low or failed retest from above with stop 1 tick below sweep low.',
    defaultNextAction: 'Wait for the morning low sweep failure to confirm on the Lunch 5M execution chart.',
  },
  {
    setupType: SetupType.LunchCompressionBreakout,
    role: 'deprecated',
    label: 'Lunch Compression Breakout',
    aliases: ['Lunch Coil Breakout', 'Midday Compression Breakout'],
    priority: 78,
    allowedSessions: LUNCH_SESSIONS,
    detectionKeywords: ['lunch compression breakout', 'midday compression', 'lunch coil', 'compression breakout'],
    possibleKeywords: ['compression', 'coil', 'tight range', 'midday range'],
    requiredEvidence: ['Completed Morning window context', 'Defined morning/lunch range', 'Compression before break', '5M breakout trigger', 'Stop outside compression boundary or active swing'],
    defaultRequiredTrigger: '5M break from compression range with stop beyond the opposite compression boundary or active swing.',
    defaultNextAction: 'Wait for the lunch compression range to break cleanly and pass risk.',
  },
  {
    setupType: SetupType.LunchFailedContinuation,
    role: 'deprecated',
    label: 'Lunch Failed Continuation',
    aliases: ['Failed Continuation', 'Midday Continuation Failure'],
    priority: 86,
    allowedSessions: LUNCH_SESSIONS,
    detectionKeywords: ['lunch failed continuation', 'failed continuation', 'continuation failure'],
    possibleKeywords: ['extended morning move', 'continuation failed', 'exhaustion', 'failed push'],
    requiredEvidence: ['Completed Morning window context', 'Morning directional move', 'Attempted lunch continuation', 'Failure at or near morning extreme/key level', '5M reversal confirmation'],
    defaultRequiredTrigger: '5M reversal confirmation after the continuation attempt fails at the morning extreme or key level.',
    defaultNextAction: 'Wait for continuation failure to confirm before planning the reversal.',
  },
  {
    setupType: SetupType.LunchRangeReclaim,
    role: 'deprecated',
    label: 'Lunch Range Reclaim',
    aliases: ['Midday Range Reclaim', 'Lunch Range Re-entry'],
    priority: 82,
    allowedSessions: LUNCH_SESSIONS,
    detectionKeywords: ['lunch range reclaim', 'range reclaim', 'reclaim morning range'],
    possibleKeywords: ['reclaim', 'back inside range', 'range re-entry', 'failed range break'],
    requiredEvidence: ['Completed Morning window context', 'Morning range or lunch range defined', 'Price leaves range', '5M reclaim back into range', 'Stop beyond failed break extreme'],
    defaultRequiredTrigger: '5M reclaim back inside the defined range with stop beyond the failed break extreme.',
    defaultNextAction: 'Wait for the range reclaim candle to close and confirm risk.',
  },
];

export const REGISTERED_SETUP_TYPES = SETUP_REGISTRY.map((entry) => entry.setupType);

/**
 * @deprecated Use REGISTERED_SETUP_TYPES. The registry lists known setup metadata;
 * execution approval still belongs to the deterministic trade decision pipeline.
 */
export const APPROVED_SETUP_TYPES = REGISTERED_SETUP_TYPES;

export function getPrimarySetupRegistry(sessionType: SetupSession): SetupRegistryEntry[] {
  return SETUP_REGISTRY.filter((entry) => entry.role === 'primary_model' && entry.allowedSessions.includes(sessionType));
}

export function getSupportingEvidenceRegistry(sessionType: SetupSession): SetupRegistryEntry[] {
  return SETUP_REGISTRY.filter((entry) => entry.role === 'supporting_evidence' && entry.allowedSessions.includes(sessionType));
}

export function getDeprecatedSetupRegistry(sessionType: SetupSession): SetupRegistryEntry[] {
  return SETUP_REGISTRY.filter((entry) => entry.role === 'deprecated' && entry.allowedSessions.includes(sessionType));
}

/**
 * @deprecated Use getPrimarySetupRegistry or getSupportingEvidenceRegistry.
 * This currently returns all allowed registry entries for backward compatibility.
 */
export function getAllowedSetupRegistry(sessionType: SetupSession): SetupRegistryEntry[] {
  return SETUP_REGISTRY.filter((entry) => entry.allowedSessions.includes(sessionType));
}
