ALTER TABLE setups
ADD COLUMN IF NOT EXISTS execution_5m_screenshot_url TEXT,
ADD COLUMN IF NOT EXISTS execution_5m_storage_path TEXT,
ADD COLUMN IF NOT EXISTS eth_15m_context_screenshot_url TEXT,
ADD COLUMN IF NOT EXISTS eth_15m_context_storage_path TEXT,
ADD COLUMN IF NOT EXISTS execution_timeframe TEXT CHECK (execution_timeframe IN ('5m') OR execution_timeframe IS NULL),
ADD COLUMN IF NOT EXISTS context_timeframe TEXT CHECK (context_timeframe IN ('15m') OR context_timeframe IS NULL),
ADD COLUMN IF NOT EXISTS context_session TEXT CHECK (context_session IN ('ETH') OR context_session IS NULL),
ADD COLUMN IF NOT EXISTS context_window_start TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS context_window_end TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS eth_context_available BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS eth_context_status TEXT CHECK (eth_context_status IN ('detected','missing','unclear') OR eth_context_status IS NULL),
ADD COLUMN IF NOT EXISTS eth_high NUMERIC,
ADD COLUMN IF NOT EXISTS eth_low NUMERIC,
ADD COLUMN IF NOT EXISTS asian_high NUMERIC,
ADD COLUMN IF NOT EXISTS asian_low NUMERIC,
ADD COLUMN IF NOT EXISTS london_high NUMERIC,
ADD COLUMN IF NOT EXISTS london_low NUMERIC,
ADD COLUMN IF NOT EXISTS ny_premarket_high NUMERIC,
ADD COLUMN IF NOT EXISTS ny_premarket_low NUMERIC,
ADD COLUMN IF NOT EXISTS rth_open_relation_to_eth TEXT CHECK (rth_open_relation_to_eth IN ('above_eth_high','below_eth_low','inside_eth_range','at_eth_high','at_eth_low','unknown') OR rth_open_relation_to_eth IS NULL),
ADD COLUMN IF NOT EXISTS rth_open_relation_to_midnight TEXT CHECK (rth_open_relation_to_midnight IN ('above','below','at','unknown') OR rth_open_relation_to_midnight IS NULL),
ADD COLUMN IF NOT EXISTS eth_context_json JSONB,
ADD COLUMN IF NOT EXISTS trade_plan_json JSONB,
ADD COLUMN IF NOT EXISTS execution_review_json JSONB,
ADD COLUMN IF NOT EXISTS eth_context_review_json JSONB,
ADD COLUMN IF NOT EXISTS midnight_open_review_json JSONB,
ADD COLUMN IF NOT EXISTS afternoon_test_plan_json JSONB;

ALTER TABLE trade_embeddings
ADD COLUMN IF NOT EXISTS execution_5m_screenshot_url TEXT,
ADD COLUMN IF NOT EXISTS execution_5m_storage_path TEXT,
ADD COLUMN IF NOT EXISTS eth_15m_context_screenshot_url TEXT,
ADD COLUMN IF NOT EXISTS eth_15m_context_storage_path TEXT,
ADD COLUMN IF NOT EXISTS execution_timeframe TEXT CHECK (execution_timeframe IN ('5m') OR execution_timeframe IS NULL),
ADD COLUMN IF NOT EXISTS context_timeframe TEXT CHECK (context_timeframe IN ('15m') OR context_timeframe IS NULL),
ADD COLUMN IF NOT EXISTS context_session TEXT CHECK (context_session IN ('ETH') OR context_session IS NULL),
ADD COLUMN IF NOT EXISTS context_window_start TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS context_window_end TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS eth_context_available BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS eth_context_status TEXT CHECK (eth_context_status IN ('detected','missing','unclear') OR eth_context_status IS NULL),
ADD COLUMN IF NOT EXISTS eth_high NUMERIC,
ADD COLUMN IF NOT EXISTS eth_low NUMERIC,
ADD COLUMN IF NOT EXISTS asian_high NUMERIC,
ADD COLUMN IF NOT EXISTS asian_low NUMERIC,
ADD COLUMN IF NOT EXISTS london_high NUMERIC,
ADD COLUMN IF NOT EXISTS london_low NUMERIC,
ADD COLUMN IF NOT EXISTS ny_premarket_high NUMERIC,
ADD COLUMN IF NOT EXISTS ny_premarket_low NUMERIC,
ADD COLUMN IF NOT EXISTS rth_open_relation_to_eth TEXT CHECK (rth_open_relation_to_eth IN ('above_eth_high','below_eth_low','inside_eth_range','at_eth_high','at_eth_low','unknown') OR rth_open_relation_to_eth IS NULL),
ADD COLUMN IF NOT EXISTS rth_open_relation_to_midnight TEXT CHECK (rth_open_relation_to_midnight IN ('above','below','at','unknown') OR rth_open_relation_to_midnight IS NULL),
ADD COLUMN IF NOT EXISTS eth_context_json JSONB,
ADD COLUMN IF NOT EXISTS trade_plan_json JSONB,
ADD COLUMN IF NOT EXISTS execution_review_json JSONB,
ADD COLUMN IF NOT EXISTS eth_context_review_json JSONB,
ADD COLUMN IF NOT EXISTS midnight_open_review_json JSONB,
ADD COLUMN IF NOT EXISTS afternoon_test_plan_json JSONB;
